config/routes.rb
Rails.application.routes.draw do

  resources :clients
  devise_for :users
  resources :posts

  #devise_for :users
  #resources :friends
  #get 'home/index'
  get 'home/about'
  get 'home/uslugi'
  get 'home/klienci'
  get 'home/kontakt'
  get 'home/artykuly'
  get 'home/forum'
  get 'home/mojaksiazka'
  root 'home#index'
# root 'friends#index'
scope module: 'users' do
  resources :posts do
  resources :elements
  
  
end
end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/client.rb
class Client < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", small: "200x200>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  validates :image, attachment_presence: true
end

app/models/post.rb
class Post < ApplicationRecord
	has_rich_text :body
	belongs_to :user, :optional => true
	has_attached_file :avatar, styles: { medium: "300x300>", small: "200x200>", thumb: "150x150>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  validates :avatar, attachment_presence: true

  def isadmin?
      current_user.isadmin? 
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
	has_many :posts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
		helper_method :logged_in?
    helper_method :isadmin?


  def logged_in?
    current_user
  end

  def require_user
    if !logged_in?
      flash[:alert] = "You must be logged in to perform that action"
      redirect_to new_user_session_path
    end
  end

  def isadmin?
    if logged_in?
      current_user.isadmin?
    end    
  end

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: %i[ show edit update destroy ]

  # GET /clients or /clients.json
  def index
    @clients = Client.paginate(page: params[:page], per_page: 5)
  end

  # GET /clients/1 or /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients or /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to client_url(@client), notice: "Client was successfully created." }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1 or /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to client_url(@client), notice: "Client was successfully updated." }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1 or /clients/1.json
  def destroy
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url, notice: "Client was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def client_params
      params.require(:client).permit(:name, :pet, :content, :image)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[ new edit update destroy ]
  before_action :authenticate_admin , only: [:new, :edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit

  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    def authenticate_admin
      redirect_to post_path, alert: 'Not authorized.' unless current_user && isadmin?
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :avatar)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
	ALERT_TYPES = [:success, :info, :warning, :danger] unless const_defined?(:ALERT_TYPES)

  def bootstrap_flash(options = {})
    flash_messages = []
    flash.each do |type, message|
      # Skip empty messages, e.g. for devise messages set to nothing in a locale file.
      next if message.blank?

      type = type.to_sym
      type = :success if type == :notice
      type = :danger  if type == :alert
      type = :danger  if type == :error
      next unless ALERT_TYPES.include?(type)

      tag_class = options.extract!(:class)[:class]
      tag_options = {
        class: "alert fade in alert-#{type} #{tag_class}"
      }.merge(options)

      close_button = content_tag(:button, raw("&times;"), type: "button", class: "close", "data-dismiss" => "alert")

      Array(message).each do |msg|
        text = content_tag(:div, close_button + msg, tag_options)
        flash_messages << text if msg
      end
    end
    flash_messages.join("\n").html_safe
  end

  def gravatar_for(user, options = { size: 80})
    email_address = user.email.downcase
    hash = Digest::MD5.hexdigest(email_address)
    size = options[:size]
    gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
    image_tag(gravatar_url, alt: user.username, class: "rounded shadow mx-auto d-block")
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <% if caption = blob.try(:caption) %>
    <figcaption class="attachment__caption">
      <%= caption %>
    </figcaption>
  <% end %>
</figure>

app/views/clients/_form.html.erb
<%= form_with(model: client) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
        <% client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :pet %>
    <%= form.text_field :pet %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1 class="text-center mt-4">Zadowoleni Klienci</h1>

<div class="flickr_pagination">
  <%= will_paginate @clients%>
</div>

<div class="container">
  <% @clients.each do |client| %>
    <div class="row justify-content-md-center">
      <div class="col-8 mt-4">
        <div class="card text-center shadow mb-5 bg-white rounded">
          <div class="card-header font-italic">
            <%#= link_to client.clientname, client %>
          </div>
          <div class="card-body">
            <h5 class="card-title">
              <%= client.name %>
            </h5>              
            <div class="img">
              <%= image_tag client.image.url(:medium)%> 
            </div>
            <p class="card-text"><%= client.pet %></p>
            <p class="card-text"><%= client.content %> </p>
            <%= link_to "View profile", client, class: "btn btn-outline-success" %>
            <% if logged_in? %>
              <% if isadmin? %>
                <%= link_to "Edit profile", edit_client_path(client), class: "btn btn-outline-info" %>
              <% end %>
              <% if isadmin? %>
                <%= link_to "Delete client", client_path(client), class: "btn btn-outline-danger", method: :delete,
                data: {confirm: "Are you sure you want to delete the client account and all associated articles?"} %>
              <% end %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Joined <%= time_ago_in_words(client.created_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Pet:</strong>
  <%= @client.pet %>
</p>

<p>
  <strong>Content:</strong>
  <%= @client.content %>
</p>

<p>
  <strong>Image:</strong>
  <%= link_to @client.image.filename, @client.image if @client.image.attached? %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
  	<%= link_to 'Strona głowna', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
      <%= link_to "O mnie", home_about_path, class:"nav-link" %> 
      </li>
                      <li class="nav-item">
                              <%= link_to "Usługi", home_uslugi_path, class:"nav-link" %> 
      </li>
                      <li class="nav-item">
                              <%= link_to "Zadowoleni klienci", clients_path, class:"nav-link" %> 
      </li>
                      <li class="nav-item">

      <%= link_to "Kontakt", home_kontakt_path, class:"nav-link" %> 
      </li>
                      <li class="nav-item">

      <%= link_to "Artykuły", posts_path, class:"nav-link" %> 
      </li>
                      <li class="nav-item">

      <%= link_to "Moja ksiązka", home_mojaksiazka_path, class:"nav-link" %> 
      </li>

                
<% if user_signed_in? %>
                        <li class="nav-item">
      <%= link_to "Wyloguj", destroy_user_session_path, method: :delete, class:"nav-link" %> 
        </li>

                        <li class="nav-item">
      <%= link_to "Edytuj profil", edit_user_registration_path, class:"nav-link" %> 
        </li>
          <% if isadmin? %>
            <li class="nav-item">
          <%= link_to "Dodaj Artykuł", new_post_path, class:"nav-link" %> 
            </li>
          <% end %>
        <% else  %>
                        <li class="nav-item">
      <%= link_to "Zarejestruj się", new_user_registration_path, class:"nav-link" %> 
        </li>

                        <li class="nav-item">
      <%= link_to "Zaloguj", new_user_session_path, class:"nav-link" %> 
        </li>
        <% end %>
          </ul>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<div class="container" id="home-container">
  <div class="text-center text-black">
    <div class="container">
      <h1 class="display-4">Przybij Lape</h1> <br />
      <div class="row">
        <div class="col">
              <p class="lead"><img src="https://static.wixstatic.com/media/1a5b8a_ba35a95991e54ad1afcd5eed82d39cbe~mv2_d_1511_2015_s_2.jpg/v1/fill/w_595,h_794,al_c,q_85,usm_0.66_1.00_0.01/30167181_583487598681135_608079252483447.webp" alt="30167181_583487598681135_608079252483447" style="width:595px;height:700px;object-fit:cover;object-position:50% 50%"></p>
        </div>
        <div class="col">
          <p class="lead"><img src="https://static.wixstatic.com/media/1a5b8a_7872e548c82642ba92035f894fd2cbfb~mv2.jpg/v1/fill/w_178,h_170,al_c,q_80,usm_0.66_1.00_0.01/6.webp" alt="6.jpg" style="width: 178px; height: 170px; object-fit: cover; object-position: 50% 50%;"></p>
          <p class="text-success" id="home-about">- Trening z psami oraz porady behawioralne na terenie Trójmiasta. </p>
          <p class="text-success" id="home-about">- Zajęcia grupowe. </p>
          <p class="text-success" id="home-about">- Ciekawe oraz pomocne artykuły o psach. </p>
          </p>
        </div>   
      </div> 
      <br /><br />
             <div class="row justify-content-center">
               <div class="col-8">
                    <h1 class="display-4">Co nieco o mnie</h1> <br />
                    <p class="text-muted" id="home-about">
                    Od dziecka pasjonuje mnie świat psów. Nigdy nie mogłam mieć swojego pupila więc swoją przygodę rozpoczęłam od wyprowadzania psów sąsiadów oraz zajmowania się nimi. W między czasie edukowałam się czytając multum książek oraz oglądając przeróżne programy. Z czasem stałam się Psią Nianią i połączyłam przyjemne z pożytecznym. Przez trzy lata mieszkałam w Anglii i tam wyprowadzałam psy ze schroniska. Było to cudowne doświadczenie jakiego nigdy nie zapomnę. Aktualnie zajmuje się trenowaniem psiaków oraz behawiorystką. Pomagam ludziom zrozumieć ich psy, zyskać pewność siebie oraz pokazuje jak z nimi współpracować. Psy to całe moje życie i uwielbiam je szkolić oraz poznawać ciekawych ludzi. </p>
              </div>
            </div>
            <br /><br />
              <div class="row justify-content-center">
               <div class="col-8">
                    <h1 class="display-4">Usługi</h1> <br />
                          <div class="row">
                            <div class="col">
                              <div class="card" style="width: 26rem;">
                                <div class="card-body">
                                  <h3 class="card-title" id="home-card-title">KONSULTACJE BEHAWIORALNE</h3>
                                  <p class="card-text" id="home-uslugi">Podczas godzinnego spotkania zapoznaje się z problemem Twojego pieska. Obserwuję zarówno jego zachowanie, jak i Twoje oraz analizuje popełniane błędy. Następnie tłumaczę oraz pokazuję jak ćwiczyć z psem, aby wyeliminować dany problem. Dodatkowo oferuję pomoce naukowe oraz stały kontakt ze mną..</p>
                                </div>
                              </div>
                            </div>
                            <div class="col">
                              <div class="card" style="width: 26rem;">
                                <div class="card-body">
                                  <h3 class="card-title" id="home-card-title">KONSULTACJE ON-LINE</h3>
                                  <p class="card-text" id="home-uslugi">Jeżeli w okolicy Twojego zamieszkania nie ma behawiorysty, to chętnie pomogę Ci na odległość, oczywiście w miarę możliwości. Konsultacje polegają na stałym kontakcie, rozmowie telefonicznej lub na Skype. Wystarczy, że w mailu wyślesz mi filmik z udziałem swojego psa, pokazując oraz opisując jego problem.</p>
                                </div>
                              </div>
                            </div>
                            <div class="col">
                              <div class="card" style="width: 26rem;">
                                <div class="card-body">
                                  <h3 class="card-title" id="home-card-title">SPOTKANIA GRUPOWE</h3>
                                  <p class="card-text" id="home-uslugi">Na zajęciach spotykamy się zarówno ze szczeniakami, jak i starszymi psami. Uczymy ich nie tylko podstawowych komend, ale również socjalizacji oraz radzenia sobie w życiu codziennym.</p>
                                </div>
                              </div>
                            </div>
                          </div>
                          </div>

              <div class="row justify-content-center">
                         <div class="col-12"><br /> <br /> 
                          <h1 class="display-4">ZADOWOLENI KLIENCI</h1> <br />
                          <div class="row">
                            <div class="col">
                              <img src="https://static.wixstatic.com/media/1a5b8a_ba35a95991e54ad1afcd5eed82d39cbe~mv2_d_1511_2015_s_2.jpg/v1/fill/w_595,h_794,al_c,q_85,usm_0.66_1.00_0.01/30167181_583487598681135_608079252483447.webp" alt="30167181_583487598681135_608079252483447" style="width:250px;height:175px;object-fit:cover;object-position:50% 50%">
                            </div>
                            <div class="col">
                              <img src="https://static.wixstatic.com/media/1a5b8a_ba35a95991e54ad1afcd5eed82d39cbe~mv2_d_1511_2015_s_2.jpg/v1/fill/w_595,h_794,al_c,q_85,usm_0.66_1.00_0.01/30167181_583487598681135_608079252483447.webp" alt="30167181_583487598681135_608079252483447" style="width:250px;height:175px;object-fit:cover;object-position:50% 50%">
                            </div>
                            <div class="col">
                              <img src="https://static.wixstatic.com/media/1a5b8a_ba35a95991e54ad1afcd5eed82d39cbe~mv2_d_1511_2015_s_2.jpg/v1/fill/w_595,h_794,al_c,q_85,usm_0.66_1.00_0.01/30167181_583487598681135_608079252483447.webp" alt="30167181_583487598681135_608079252483447" style="width:250px;height:175px;object-fit:cover;object-position:50% 50%">
                            </div>
                            <div class="col">
                              <img src="https://static.wixstatic.com/media/1a5b8a_ba35a95991e54ad1afcd5eed82d39cbe~mv2_d_1511_2015_s_2.jpg/v1/fill/w_595,h_794,al_c,q_85,usm_0.66_1.00_0.01/30167181_583487598681135_608079252483447.webp" alt="30167181_583487598681135_608079252483447" style="width:250px;height:175px;object-fit:cover;object-position:50% 50%">
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
<br /> <br /> <br /> <br /> 
              </div>
            </div>
    </div>
  </div>
</div>

app/views/home/artykuly.html.erb
<% #https://getbootstrap.com/docs/5.1/components/card/%>
<div class="card-group">
  <div class="card">
    <img src="https://static.wixstatic.com/media/1a5b8a_d5c576065bb94721997883044bfcfb24~mv2.jpg/v1/fill/w_454,h_341,fp_0.50_0.50,q_90/1a5b8a_d5c576065bb94721997883044bfcfb24~mv2.webp" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://static.wixstatic.com/media/1a5b8a_d5c576065bb94721997883044bfcfb24~mv2.jpg/v1/fill/w_454,h_341,fp_0.50_0.50,q_90/1a5b8a_d5c576065bb94721997883044bfcfb24~mv2.webp" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This card has supporting text below as a natural lead-in to additional content.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
  <div class="card">
    <img src="https://static.wixstatic.com/media/1a5b8a_d5c576065bb94721997883044bfcfb24~mv2.jpg/v1/fill/w_454,h_341,fp_0.50_0.50,q_90/1a5b8a_d5c576065bb94721997883044bfcfb24~mv2.webp" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This card has even longer content than the first to show that equal height action.</p>
      <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
    </div>
  </div>
</div>

app/views/home/uslugi.html.erb
<div class="container" id="home-container">
  <div class="text-center text-black">
    <div class="container">
              <div class="row justify-content-center">
               <div class="col-12">
                    <h1 class="display-4">Usługi</h1> <br />
                          <div class="row">
                            <div class="col">
                                  <h3 class="card-title" id="home-card-title">KONSULTACJE BEHAWIORALNE</h3>
                                  <p class="card-text" id="home-uslugi">Podczas godzinnego spotkania zapoznaje się z problemem Twojego pieska. Obserwuję zarówno jego zachowanie, jak i Twoje oraz analizuje popełniane błędy. Następnie tłumaczę oraz pokazuję jak ćwiczyć z psem, aby wyeliminować dany problem. Dodatkowo oferuję pomoce naukowe oraz stały kontakt ze mną..</p>
                            </div>
                            <div class="col">
                                  <h3 class="card-title" id="home-card-title">KONSULTACJE ON-LINE</h3>
                                  <p class="card-text" id="home-uslugi">Jeżeli w okolicy Twojego zamieszkania nie ma behawiorysty, to chętnie pomogę Ci na odległość, oczywiście w miarę możliwości. Konsultacje polegają na stałym kontakcie, rozmowie telefonicznej lub na Skype. Wystarczy, że w mailu wyślesz mi filmik z udziałem swojego psa, pokazując oraz opisując jego problem.</p>
                            </div>
                            <div class="col">
                                  <h3 class="card-title" id="home-card-title">SPOTKANIA GRUPOWE</h3>
                                  <p class="card-text" id="home-uslugi">Na zajęciach spotykamy się zarówno ze szczeniakami, jak i starszymi psami. Uczymy ich nie tylko podstawowych komend, ale również socjalizacji oraz radzenia sobie w życiu codziennym.</p>
                            </div>
                          </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright Krzycho Borucki</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %> 
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <head>
    <title>Przybij Lape</title>
  </head>
  <body class="d-flex flex-column">
    <%= render 'home/header' %>
    <div class="container">
      <br/>
      <% if notice %>
      <%= render 'layouts/alerts' %>
    <% end %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
    <%= yield %>
  </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/mailer.html (copy).erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/mailer.text (copy).erb
<%= yield %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Artykuły</h1>
<div class="container">
          <% @posts.each do |post| %>
  <div class="row justify-content-center">

    <div class="card mb-3" style="max-width: 800px;">
      <div class="row g-0">
        <div class="col-md-7">
            <% if isadmin? %>
              <%= link_to edit_post_path(post) do %>  
              <div class="img">
              <%= image_tag post.avatar.url(:medium)%> 
              </div>
            <% end %>
            <% elsif %>
              <%= link_to post do %>  
              <div class="img">
              <%= image_tag post.avatar.url(:medium)%> 
              </div>
            <% end %>
          <% end %>
        </div>
          <div class="col-md-5">
            <div class="card-body">
              <h5 class="card-title"><%= post.title %></h5>
              <p class="card-text"><%= post.body %></p>
        </div>
                              <div class="card-footer text-muted">
                  Utworzony: <%= post.created_at %>
                </div>
      </div>
    </div>
    <br />

  </div>
      <% end %>
</div>
</div>


<% if isadmin? %>
  <%= link_to 'New Post', new_post_path, class: 'btn btn-primary'%>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

  <h1 class="text-center"><%= @post.title %> </h1>
<br />
<div class="container">
  <%= @post.body %>
</div>

<%= link_to 'Back', posts_path %>